# Generated by Django 6.0.6 on 2026-06-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Desk Mats', 'Desk Mats'), ('Audio', 'Audio'), ('Lighting', 'Lighting'), ('Accessories', 'Accessories')], default='Electronics', max_length=50),
        ),
    ]
