databases:
  - name: auradb
    plan: free

services:
  - type: web
    name: aura-store
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn ecommerce_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auradb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".render.com"
      - key: MONGO_URI
        sync: false
